-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\hpa_module\hpa_module_dut.vhd
-- Created: 2021-12-20 09:42:20
-- 
-- Generated by MATLAB 9.8 and HDL Coder 3.16
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: hpa_module_dut
-- Source Path: hpa_module/hpa_module_dut
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY hpa_module_dut IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        dut_enable                        :   IN    std_logic;  -- ufix1
        AXI4_Reset                        :   IN    std_logic;  -- ufix1
        s_img_axis_tvalid                 :   IN    std_logic;  -- ufix1
        s_img_axis_tdata                  :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        s_img_axis_tlast                  :   IN    std_logic;  -- ufix1
        s_hps_axis_tvalid                 :   IN    std_logic;  -- ufix1
        s_hps_axis_tdata                  :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        s_hps_axis_tlast                  :   IN    std_logic;  -- ufix1
        ce_out                            :   OUT   std_logic;  -- ufix1
        AXI4_ClockCycles                  :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        AXI4_Overflow                     :   OUT   std_logic;  -- ufix1
        s_img_axis_tready                 :   OUT   std_logic;  -- ufix1
        s_hps_axis_tready                 :   OUT   std_logic  -- ufix1
        );
END hpa_module_dut;


ARCHITECTURE rtl OF hpa_module_dut IS

  -- Component Declarations
  COMPONENT hpa_module_src_Hough_Performance_Analyser
    PORT( clk                             :   IN    std_logic;
          clk_enable                      :   IN    std_logic;
          reset                           :   IN    std_logic;
          AXI4_Reset                      :   IN    std_logic;  -- ufix1
          s_img_axis_tvalid               :   IN    std_logic;  -- ufix1
          s_img_axis_tdata                :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          s_img_axis_tlast                :   IN    std_logic;  -- ufix1
          s_hps_axis_tvalid               :   IN    std_logic;  -- ufix1
          s_hps_axis_tdata                :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          s_hps_axis_tlast                :   IN    std_logic;  -- ufix1
          ce_out                          :   OUT   std_logic;  -- ufix1
          AXI4_ClockCycles                :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          AXI4_Overflow                   :   OUT   std_logic;  -- ufix1
          s_img_axis_tready               :   OUT   std_logic;  -- ufix1
          s_hps_axis_tready               :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : hpa_module_src_Hough_Performance_Analyser
    USE ENTITY work.hpa_module_src_Hough_Performance_Analyser(rtl);

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL AXI4_Reset_sig                   : std_logic;  -- ufix1
  SIGNAL s_img_axis_tvalid_sig            : std_logic;  -- ufix1
  SIGNAL s_img_axis_tlast_sig             : std_logic;  -- ufix1
  SIGNAL s_hps_axis_tvalid_sig            : std_logic;  -- ufix1
  SIGNAL s_hps_axis_tlast_sig             : std_logic;  -- ufix1
  SIGNAL ce_out_sig                       : std_logic;  -- ufix1
  SIGNAL AXI4_ClockCycles_sig             : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL AXI4_Overflow_sig                : std_logic;  -- ufix1
  SIGNAL s_img_axis_tready_sig            : std_logic;  -- ufix1
  SIGNAL s_hps_axis_tready_sig            : std_logic;  -- ufix1

BEGIN
  u_hpa_module_src_Hough_Performance_Analyser : hpa_module_src_Hough_Performance_Analyser
    PORT MAP( clk => clk,
              clk_enable => enb,
              reset => reset,
              AXI4_Reset => AXI4_Reset_sig,  -- ufix1
              s_img_axis_tvalid => s_img_axis_tvalid_sig,  -- ufix1
              s_img_axis_tdata => s_img_axis_tdata,  -- ufix32
              s_img_axis_tlast => s_img_axis_tlast_sig,  -- ufix1
              s_hps_axis_tvalid => s_hps_axis_tvalid_sig,  -- ufix1
              s_hps_axis_tdata => s_hps_axis_tdata,  -- ufix32
              s_hps_axis_tlast => s_hps_axis_tlast_sig,  -- ufix1
              ce_out => ce_out_sig,  -- ufix1
              AXI4_ClockCycles => AXI4_ClockCycles_sig,  -- ufix32
              AXI4_Overflow => AXI4_Overflow_sig,  -- ufix1
              s_img_axis_tready => s_img_axis_tready_sig,  -- ufix1
              s_hps_axis_tready => s_hps_axis_tready_sig  -- ufix1
              );

  AXI4_Reset_sig <= AXI4_Reset;

  s_img_axis_tvalid_sig <= s_img_axis_tvalid;

  s_img_axis_tlast_sig <= s_img_axis_tlast;

  s_hps_axis_tvalid_sig <= s_hps_axis_tvalid;

  s_hps_axis_tlast_sig <= s_hps_axis_tlast;

  enb <= dut_enable;

  ce_out <= ce_out_sig;

  AXI4_ClockCycles <= AXI4_ClockCycles_sig;

  AXI4_Overflow <= AXI4_Overflow_sig;

  s_img_axis_tready <= s_img_axis_tready_sig;

  s_hps_axis_tready <= s_hps_axis_tready_sig;

END rtl;

